### ISSUE TITLE
Didn't understand 

### ISSUE THREAD

**Issue by StrikeNew** [xHaruke/Simple-DankGrinder#2]
Didn't understand time format

**Comment by xHaruke** [comment]
you have to use 24hr format and use only the hour value e.g. 14

**Comment by Clumsy-Assassin** [comment]
@xHaruke Sorry to bother you, but I just wanted to thank you for this amazing bot! More than that I thank you for showing us how to deploy it. So many devs leave that part not realizing that many people do not know how to do it.
Other than that, I was wondering if I could simply close the URL I entered in the monitor website, as well as the monitor website itself. Do I have to keep any of the two open while I work?
And once again, Thank You!

**Comment by xHaruke** [comment]
@Clumsy-Assassin Yes you can close it, you can even your computer and it'll still be working.. Thats what 24*7 means
