### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'cache')

### ISSUE THREAD

**Issue by roclcly** [xHaruke/Simple-DankGrinder#3]
Shows this in the logs.
<img width="932" alt="image" src="https://user-images.githubusercontent.com/101468419/177533614-10304fba-be9c-4994-8eca-336c9c447fe2.png">
This is the config vars:
![image](https://user-images.githubusercontent.com/101468419/177533929-41b9b54f-8272-491a-9301-9969ed568fff.png)

**Comment by xHaruke** [comment]
just restart the dyno

**Comment by xHaruke** [comment]
> Shows this in the logs.
> <img width="932" alt="image" src="https://user-images.githubusercontent.com/101468419/177533614-10304fba-be9c-4994-8eca-336c9c447fe2.png">
> This is the config vars:
> ![image](https://user-images.githubusercontent.com/101468419/177533929-41b9b54f-8272-491a-9301-9969ed568fff.png)
> 

just restart the dyno
